### ISSUE TITLE
🎯 Docker

### ISSUE THREAD

**Issue by Lordpedal** [jmarcet/movistar-u7d#1]
Buenas tardes,

He estado revisando el proyecto y tengo que decir que tiene una pinta excelente en concepto y a priori por el funcionamiento que aportas en los videos documentados parece que tiene un funcionamiento sensacional.

[UDPXY](https://github.com/Lordpedal/udpxy) puedes integrarlo en el docker-compose para hacer el sistema lo más portable posible.

Voy a probarlo aprovechando la gestión de Docker y espero comentar experiencias de uso con el resultado obtenido.

Una duda que parametros debo de poner aquí del fichero de variables:

```bash
# docker-compose
IPTV_GW=
U7D_GW=
MAC_IPTV_U7D=
MAC_MOVISTAR_U7D=
```

**¿La puerta de enlace del servidor que corre el docker y la mac?**

Porque algo he debido de poner mal en ese apartado ya que me arroja el siguiente error:

```bash
[2021-03-20 20:50:17] [INFO] ---------------------------------------------------
[2021-03-20 20:50:17] [INFO] MovistarTV EPG Grabber
[2021-03-20 20:50:17] [INFO] Parámetros: ['--tvheadend', '/home/MovistarTV.m3u', '--output', '/home/guide.xml']
[2021-03-20 20:50:17] [INFO] ---------------------------------------------------
[2021-03-20 20:50:17] [INFO] Creando caché en /home/.xmltv/cache
[2021-03-20 20:50:17] [INFO] Cookie: no encontrada
[2021-03-20 20:50:17] [DEBUG] Caché: configuración no encontrada
[2021-03-20 20:50:17] [INFO] Descargando configuración del cliente
[2021-03-20 20:50:17] [DEBUG] End Points: buscando
[2021-03-20 20:50:17] [DEBUG] End Points: por defecto
[2021-03-20 20:50:17] [INFO] Descargando pefil del servicio
[2021-03-20 20:50:17] [DEBUG] End Points: buscando
[2021-03-20 20:50:17] [DEBUG] End Points: por defecto
[2021-03-20 20:50:17] [INFO] Descargando parámetros de configuración
[2021-03-20 20:50:17] [DEBUG] End Points: buscando
[2021-03-20 20:50:17] [DEBUG] End Points: por defecto
[2021-03-20 20:50:17] [INFO] tvPackages: UTXCP|UTXGW
[2021-03-20 20:50:17] [INFO] Demarcation: 12
[2021-03-20 20:50:17] [INFO] Nuevos End Points: dict_keys(['epNoCach2', 'epNoCach1', 'epNoCach4', 'epNoCach3', 'epNoCach6', 'epNoCach5', 'epNoCach8', 'epNoCach7', 'epNoCach9', 'epNoCach11', 'epNoCach10'])
[2021-03-20 20:50:17] [INFO] Descargando mapa de géneros
[2021-03-20 20:50:17] [INFO] Buscando el Proveedor de Servicios de Murcia
[2021-03-20 20:50:17] [DEBUG] Caché: datos del Proveedor de Servicios no encontrados
[2021-03-20 20:50:17] [DEBUG] Descargando XML de 239.0.2.129:3937
[2021-03-20 20:50:20] [ERROR] Error al descargar los archivos XML: timeout('timed out')
[2021-03-20 20:50:20] [ERROR] Usando el Proveedor de Servicios por defecto: 239.0.2.150
[2021-03-20 20:50:20] [DEBUG] Descargando XML de 239.0.2.150:3937
[2021-03-20 20:50:23] [ERROR] Error al descargar los archivos XML: timeout('timed out')
[2021-03-20 20:50:23] [DEBUG] Caché: metadatos de la EPG no encontrados
[2021-03-20 20:50:23] [INFO] Descargando canales y paquetes
[2021-03-20 20:50:23] [CRITICAL] TypeError("'NoneType' object is not subscriptable")
Traceback (most recent call last):
  File "/app/tv_grab_es_movistartv", line 1322, in <module>
    xdata = iptv.get_service_provider_data()
  File "/app/tv_grab_es_movistartv", line 878, in get_service_provider_data
    self.__get_epg_data(connection['mcast_grp'], connection['mcast_port'])
  File "/app/tv_grab_es_movistartv", line 869, in __get_epg_data
    'channels': self.__get_channels(xml['2_0']),
TypeError: 'NoneType' object is not subscriptable
```

Un saludo 👌

**Comment by jmarcet** [comment]
Hola @Lordpedal ,

Te agradezco tus palabras :grinning:

Con respecto al `udpxy`, tienes toda la razón, pero.

En alpine no hay paquete de `udpxy`, tenía que hacer bastante mas gordo el Dockerfile, teniéndolo en el host me permite tener los streams aún con los containers parados (como puede pasar al reiniciar o cuando tienes los containers en mantenimiento ).

Si escribes la integración al Dockerfile, lo añado, aunque sea comentado (me gusta tenerlo fuera) :smiley:

**Comment by jmarcet** [comment]
Yo lo uso dentro de este compose:

```
  movistar_u7d:                                                                                                                                                                                                                                                               
    build: ./movistar_u7d                                                                                                                                                                                                                                                     
    container_name: movistar_u7d                                                                                                                                                                                                                                              
    cap_add:                                                                                                                                                                                                                                                                  
      - NET_ADMIN                                                                                                                                                                                                                                                             
      - NET_BROADCAST                                                                                                                                                                                                                                                         
      - SYS_ADMIN                                                                                                                                                                                                                                                             
      - SYS_NICE                                                                                                                                                                                                                                                              
    restart: on-failure                                                                                                                                                                                                                                                       
    networks:                                                                                                                                                                                                                                                                 
      tvlan:                                                                                                                                                                                                                                                                  
        ipv4_address: ${U7D_ADDRESS}                                                                                                                                                                                                                                          
      iptv:                                                                                                                                                                                                                                                                   
        ipv4_address: ${IPTV_ADDRESS}                                                                                                                                                                                                                                         
    volumes:                                                                                                                                                                                                                                                                  
      - /etc/localtime:/etc/localtime                                                                                                                                                                                                                                         
      - ./movistar_u7d:/app                                                                                                                                                                                                                                                   
      - ${U7D_HOME}:/home                                                                                                                                                                                                                                                     
      - ${U7D_DIR}:${U7D_DIR}                                                                                                                                                                                                                                                 
    environment:                                                                                                                                                                                                                                                              
      - IPTV_GW=${IPTV_GW}                                                                                                                                                                                                                                                    
      - MAC_IPTV_U7D=${MAC_IPTV_U7D}                                                                                                                                                                                                                                          
      - MAC_MOVISTAR_U7D=${MAC_MOVISTAR_U7D}                                                                                                                                                                                                                                  
      - SANIC_HOST=${SANIC_HOST}                                                                                                                                                                                                                                              
      - SANIC_PORT=${SANIC_PORT}                                                                                                                                                                                                                                              
      - SANIC_EPG_HOST=${SANIC_EPG_HOST}                                                                                                                                                                                                                                      
      - SANIC_EPG_PORT=${SANIC_EPG_PORT}                                                                                                                                                                                                                                      
      - U7D_GW=${U7D_GW}                                                                                                                                                                                                                                                      
      - U7D_DIR=${U7D_DIR}                                                                                                                                                                                                                                                    
      - UDPXY=${UDPXY}                                                                                                                                                                                                                                                        
    devices:                                                                                                                                                                                                                                                                  
      - /dev/dri:/dev/dri                                                                                                                                                                                                                                                     
    cpu_shares: 4096                                                                                                                                                                                                                                                          
    cpus: 4                                                                                                                                                                                                                                                                   
    mem_limit: 1gb                                                                                                                                                                                                                                                            
    memswap_limit: 1gb                                                                                                                                                                                                                                                        
    healthcheck:                                                                                                                                                                                                                                                              
      test: /app/health.sh                                                                                                                                                                                                                                                    
      interval: 300s                                                                                                                                                                                                                                                          
      timeout: 5s                                                                                                                                                                                                                                                             
      retries: 3

networks:
  iptv:
    driver: macvlan
    driver_opts:
      parent: eth0.2
    ipam:
      config:
         - subnet: ${IPTV_NET}
  tvlan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_TVLAN}
    driver_opts:
      com.docker.network.bridge.name: br-tvlan
```

Donde:

```
IPTV_ADDRESS=a.b.c.d # IP_DE_LA_VLAN_2_DE_MOVISTAR
IPTV_GW=10.64.0.1
IPTV_NET=10.64.0.0/12

U7D_ADDRESS=10.17.0.3 # UP
U7D_DIR=/storage/u7d
U7D_GW=10.17.0.1 # GW de la subred 
U7D_HOME=/opt/xmltv

MAC_IPTV_U7D=aa:bb:cc:dd:ee:02 #mac del eth0 dentro del docker, q corresponde a la subred maclvan *iptv*
MAC_MOVISTAR_U7D=aa:bb:cc:dd:ee:03 #mac del eth1 dentro del docker, que corresponde al bridge *tvlan*

SUBNET_TVLAN=10.17.0.0/24 # la subred del los U7D_ de arriba
```

Dentro del docker queda así:
```
$ docker exec -it movistar_u7d bash
bash-5.1# ifconfig 
eth0      Link encap:Ethernet  HWaddr aa:bb:cc:dd:ee:02  
          inet addr:10.b.c.d  Bcast:10.79.255.255  Mask:255.240.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:114617702 errors:0 dropped:0 overruns:0 frame:0
          TX packets:95953 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:155213758683 (144.5 GiB)  TX bytes:17217040 (16.4 MiB)

eth1      Link encap:Ethernet  HWaddr aa:bb:cc:dd:ee:03  
          inet addr:10.17.0.3  Bcast:10.x.y.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:57706112 errors:0 dropped:0 overruns:0 frame:0
          TX packets:114444302 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:4150881922 (3.8 GiB)  TX bytes:159115663631 (148.1 GiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:29043 errors:0 dropped:0 overruns:0 frame:0
          TX packets:29043 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2909305 (2.7 MiB)  TX bytes:2909305 (2.7 MiB)

bash-5.1#
```

Claro, olvidaba que hace falta una pieza más en el host, tengo que actualizar la documentación. Hace falta un [igmpproxy](https://github.com/pali/igmpproxy) en el host con una configuración similar a:

```
$ cat /etc/igmpproxy.conf
quickleave

phyint eth0.2 upstream ratelimit 0 threshold 1
        altnet 172.0/11

phyint br-tvlan downstream ratelimit 0 threshold 1
```

`eth0.2` es la VLAN2 de movistar, `br-tvlan` es el bridge `tvlan` del docker.
